parameters:
  min_samples_leaf: 1
  learning_rate: 0.1

experiment_name_fe: /Shared/house-prices-fe

num_features:
  - no_of_adults
  - no_of_children
  - no_of_weekend_nights
  - no_of_week_nights
  - required_car_parking_space
  - lead_time
  - arrival_year
  - arrival_month
  - arrival_date
  - repeated_guest
  - no_of_previous_cancellations
  - no_of_previous_bookings_not_canceled
  - avg_price_per_room
  - no_of_special_requests

cat_features:
  - type_of_meal_plan
  - room_type_reserved
  - market_segment_type

one_hot_encode_cols:
  - market_segment_type
  - type_of_meal_plan
  - room_type_reserved
  - quarter

columns_to_drop:
  - arrival_year
  - arrival_date
  - arrival_month

features_used:
  - no_of_adults
  - no_of_children
  - no_of_weekend_nights
  - no_of_week_nights
  - required_car_parking_space
  - lead_time
  - repeated_guest
  - no_of_previous_cancellations
  - no_of_previous_bookings_not_canceled
  - avg_price_per_room
  - no_of_special_requests
  - market_segment_type_Complementary
  - market_segment_type_Corporate
  - market_segment_type_Offline
  - market_segment_type_Online
  - type_of_meal_plan_Meal_Plan_2
  - room_type_reserved_Room_Type_4
  - room_type_reserved_Room_Type_6
  - room_type_reserved_Room_Type_7
  - quarter_Q2
  - quarter_Q3
  - quarter_Q4

target: booking_status

catalog_name: "koen_dev"
schema_name: "gold_hotel_reservations"
